

spring:
       datasource:
         url: jdbc:mysql://localhost:3306/citymanagement?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
         username: root
         password: 322120
         driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.citymanagement.Dao
server:
    port: 8081
    servlet:
          context-path: /city